[project]
name = "repo-to-md"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pyperclip>=1.9.0",
    "rich>=14.0.0",
    "typer>=0.15.2",
]
